---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-probe-deploy
  labels:
    app: probe
spec:
  selector:
    matchLabels:
      app: probe
  replicas: 1
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: ubuntu-probe
          image: ubuntu
          command:
            - sleep 
            - "7200"

            #---
            #apiVersion: v1
            #kind: Service
            #metadata:
            #  name: probe-svc
            #  labels:
            #    app: probe
            #spec:
            #  type: LoadBalancer
            #  selector:
            #    app: probe
            #  ports:
            #    - port: 22322
            #      targetPort: 22
            #
            #--- 
            #apiVersion: v1
            #kind: Service
            #metadata:
            #  name: probe
            #  labels:
            #    app: probe
            #spec:
            #  type: ClusterIP
            #  selector:
            #    app: probe
            #  ports: 
            #    - port: 22
            #      targetPort: 22
